name: Build and Add PDF to Repository

on:
  push:
    branches:
      - main 

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Move PDF to Repository
        run: |
          mkdir -p pdf_output
          mv main.pdf pdf_output/
          git add pdf_output/main.pdf
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Add compiled PDF to repository" || true
          git push

